#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jan 01 21:16:17 EST 2026
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim testfixture_behav -key {Behavioral:sim_2:Functional:testfixture} -tclbatch testfixture.tcl -view /nfs/ug/homes-2/c/cheng520/ISML/GAP_SCI/vivado/vivado.sim/sim_2/testfixture_behav.wcfg -log simulate.log"
xsim testfixture_behav -key {Behavioral:sim_2:Functional:testfixture} -tclbatch testfixture.tcl -view /nfs/ug/homes-2/c/cheng520/ISML/GAP_SCI/vivado/vivado.sim/sim_2/testfixture_behav.wcfg -log simulate.log

