# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /nfs/ug/homes-2/c/cheng520/ISML/GAP_SCI/vivado/vivado.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
# IP: The module: 'fifo_generator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /nfs/ug/homes-2/c/cheng520/ISML/GAP_SCI/vivado/vivado.gen/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /nfs/ug/homes-2/c/cheng520/ISML/GAP_SCI/vivado/vivado.gen/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /nfs/ug/homes-2/c/cheng520/ISML/GAP_SCI/vivado/vivado.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
# IP: The module: 'fifo_generator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /nfs/ug/homes-2/c/cheng520/ISML/GAP_SCI/vivado/vivado.gen/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /nfs/ug/homes-2/c/cheng520/ISML/GAP_SCI/vivado/vivado.gen/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
